import { User, Client, Goal, Session, Homework, Strategy, Resource, JournalEntry, Parent, AuditLog } from '../types';

// Current user (can be switched for demo)
export let currentUser: User = {
  id: '1',
  name: 'Anna Martinez',
  role: 'therapist',
  email: 'anna.martinez@kidable.com',
  specializations: ['aba', 'speech'],
  status: 'active',
  lastLogin: new Date('2025-12-08T08:00:00'),
};

export const users: User[] = [
  currentUser,
  {
    id: '2',
    name: 'Dr. Sarah Chen',
    role: 'admin',
    email: 'sarah.chen@kidable.com',
    specializations: ['aba', 'speech', 'ot'],
    status: 'active',
    lastLogin: new Date('2025-12-08T07:30:00'),
  },
  {
    id: '3',
    name: 'David Williams',
    role: 'therapist',
    email: 'david.williams@kidable.com',
    specializations: ['ot'],
    status: 'active',
    lastLogin: new Date('2025-12-07T16:00:00'),
  },
];

export const parents: Parent[] = [
  {
    id: 'p1',
    name: 'Sarah Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1-555-1001',
    relationship: 'Mother',
    isPrimary: true,
    status: 'active',
    childrenIds: ['c1'],
  },
  {
    id: 'p2',
    name: 'Maria Wilson',
    email: 'maria.wilson@email.com',
    phone: '+1-555-1002',
    relationship: 'Mother',
    isPrimary: true,
    status: 'active',
    childrenIds: ['c2'],
  },
  {
    id: 'p3',
    name: 'John Brown',
    email: 'john.brown@email.com',
    phone: '+1-555-1003',
    relationship: 'Father',
    isPrimary: true,
    status: 'active',
    childrenIds: ['c3'],
  },
];

export const clients: Client[] = [
  {
    id: 'c1',
    firstName: 'Alex',
    lastName: 'Johnson',
    dateOfBirth: new Date('2020-05-20'),
    age: 5,
    therapyStartDate: new Date('2025-09-01'),
    therapyTypes: ['aba', 'speech', 'ot'],
    status: 'active',
    primaryTherapistId: '1',
    primaryCaregiverId: 'p1',
    preferences: ['Dinosaurs', 'Building blocks', 'Drawing', 'Bubbles', 'Trains'],
    dislikes: ['Loud music', 'Crowded spaces', 'Unexpected transitions'],
    sensoryProfile: {
      visual: 'Prefers dim lighting, avoids fluorescent',
      auditory: 'Sensitive to sudden loud noises',
      tactile: 'Enjoys deep pressure, dislikes light touch',
      vestibular: 'Seeks movement, loves swinging',
      proprioceptive: 'Needs heavy work activities',
    },
    communicationStyles: ['Verbal (2-3 word phrases)', 'Gestures', 'Picture cards'],
  },
  {
    id: 'c2',
    firstName: 'Emma',
    lastName: 'Wilson',
    dateOfBirth: new Date('2019-03-15'),
    age: 6,
    therapyStartDate: new Date('2025-06-15'),
    therapyTypes: ['aba', 'speech'],
    status: 'active',
    primaryTherapistId: '1',
    primaryCaregiverId: 'p2',
    preferences: ['Puzzles', 'Singing', 'Animals', 'Stickers'],
    dislikes: ['Sudden changes', 'Dark rooms'],
  },
  {
    id: 'c3',
    firstName: 'Michael',
    lastName: 'Brown',
    dateOfBirth: new Date('2021-08-10'),
    age: 4,
    therapyStartDate: new Date('2025-10-01'),
    therapyTypes: ['ot'],
    status: 'active',
    primaryTherapistId: '3',
    primaryCaregiverId: 'p3',
    preferences: ['Swinging', 'Climbing', 'Play-doh'],
    dislikes: ['Sticky textures', 'Tight clothing'],
  },
];

export const goals: Goal[] = [
  {
    id: 'g1',
    clientId: 'c1',
    title: 'Improve Expressive Language',
    description: 'Use 2-word phrases independently in 80% of opportunities',
    therapyType: 'speech',
    baseline: 20,
    target: 80,
    current: 65,
    status: 'active',
    dueDate: new Date('2025-12-31'),
    createdDate: new Date('2025-09-01'),
  },
  {
    id: 'g2',
    clientId: 'c1',
    title: 'Increase Eye Contact',
    description: 'Maintain eye contact for 3+ seconds during greeting',
    therapyType: 'aba',
    baseline: 10,
    target: 90,
    current: 45,
    status: 'active',
    dueDate: new Date('2025-12-31'),
    createdDate: new Date('2025-09-01'),
  },
  {
    id: 'g3',
    clientId: 'c1',
    title: 'Fine Motor Skills',
    description: 'Hold pencil with proper grasp for drawing',
    therapyType: 'ot',
    baseline: 30,
    target: 85,
    current: 70,
    status: 'active',
    createdDate: new Date('2025-09-15'),
  },
];

export const sessions: Session[] = [
  {
    id: 's1',
    clientId: 'c1',
    sessionNumber: 16,
    date: new Date('2025-12-08'),
    therapyType: 'aba',
    zone: 'green',
    therapistId: '1',
    longTermObjective: 'Develop social communication skills',
    shortTermObjective: 'Initiate play with peer 2x per session',
    activities: [
      {
        id: 'a1',
        name: 'Greeting practice',
        antecedent: 'Therapist modeled',
        behavior: 'Said "hi" independently',
        consequence: 'Verbal praise',
      },
      {
        id: 'a2',
        name: 'Turn-taking game',
        antecedent: 'Presented board game',
        behavior: 'Waited 4/5 turns',
        consequence: 'Token + high five',
      },
    ],
    successes: ['Initiated play twice', 'Waited for turn', 'Used words to request'],
    struggles: ['Difficulty maintaining eye contact', 'Became frustrated with losing'],
    interventions: ['Visual timer', 'First-then board'],
    strategies: ['Token economy', 'Social stories'],
    reinforcements: ['Stickers', 'High fives', 'Verbal praise'],
    notes: 'Great session overall. Continue working on frustration tolerance.',
    discussedWithParent: true,
  },
  {
    id: 's2',
    clientId: 'c1',
    sessionNumber: 15,
    date: new Date('2025-12-06'),
    therapyType: 'speech',
    zone: 'green',
    therapistId: '1',
    longTermObjective: 'Expand expressive vocabulary',
    shortTermObjective: 'Use 2-word phrases spontaneously',
    activities: [
      {
        id: 'a3',
        name: 'Picture labeling',
        antecedent: 'Showed favorite animal pictures',
        behavior: 'Said "big dinosaur" spontaneously',
        consequence: 'Access to toy dinosaur',
      },
    ],
    successes: ['Used 5 two-word phrases', 'Clear articulation'],
    struggles: ['Needed prompting for some phrases'],
    interventions: ['Modeling', 'Expansion'],
    strategies: ['Naturalistic teaching'],
    reinforcements: ['Dinosaur toys', 'Bubbles'],
    discussedWithParent: true,
  },
];

export const homework: Homework[] = [
  {
    id: 'h1',
    clientId: 'c1',
    title: 'Deep Breathing Exercise',
    description: '5 minutes of deep breathing practice',
    purpose: 'Help Alex self-regulate when feeling overwhelmed',
    instructions: '1. Find a quiet space\n2. Practice "smell the flower, blow the candle"\n3. Repeat 5 times',
    therapyType: 'aba',
    status: 'worked',
    assignedDate: new Date('2025-11-01'),
    assignedById: '1',
    goalId: 'g2',
    completionCount: 15,
  },
  {
    id: 'h2',
    clientId: 'c1',
    title: 'Picture Labeling Practice',
    description: 'Practice naming objects in picture book',
    purpose: 'Increase expressive vocabulary',
    therapyType: 'speech',
    status: 'worked',
    assignedDate: new Date('2025-11-15'),
    assignedById: '1',
    goalId: 'g1',
    completionCount: 8,
  },
];

export const strategies: Strategy[] = [
  {
    id: 'st1',
    title: 'Visual Schedule',
    description: 'Use a picture schedule to preview daily activities',
    type: 'antecedent',
    targetZone: 'green',
    whenToUse: 'Before transitions or new activities',
    howToUse: '1. Show the visual schedule\n2. Point to each activity in order\n3. Review what comes next',
    examples: ['Morning routine', 'Therapy session outline', 'After-school activities'],
  },
  {
    id: 'st2',
    title: 'Token Economy',
    description: 'Award tokens for desired behaviors that can be exchanged for rewards',
    type: 'reinforcement',
    whenToUse: 'Throughout the day to reinforce target behaviors',
    howToUse: '1. Define target behaviors\n2. Award tokens immediately\n3. Allow exchange for preferred items/activities',
    examples: ['Following directions', 'Using words', 'Sharing with peers'],
  },
  {
    id: 'st3',
    title: 'Deep Pressure Input',
    description: 'Apply firm, calming pressure to help with regulation',
    type: 'regulation',
    targetZone: 'yellow',
    whenToUse: 'When child shows signs of dysregulation',
    howToUse: '1. Offer weighted blanket or vest\n2. Provide squeezes or hugs\n3. Use therapy ball for pressure',
    examples: ['Weighted lap pad during circle time', 'Bear hugs', 'Rolling under therapy ball'],
  },
];

export const resources: Resource[] = [
  {
    id: 'r1',
    title: 'Sensory Processing Guide',
    description: 'A comprehensive guide to understanding sensory processing',
    type: 'pdf',
    category: 'Education',
    url: '#',
    fileSize: '2.4 MB',
  },
  {
    id: 'r2',
    title: 'Introduction to ABA',
    description: 'Video series explaining Applied Behavior Analysis principles',
    type: 'video',
    category: 'Education',
    url: '#',
  },
  {
    id: 'r3',
    title: 'Emotion Cards Worksheet',
    description: 'Printable cards for teaching emotion identification',
    type: 'worksheet',
    category: 'Activities',
    url: '#',
  },
];

export const journalEntries: JournalEntry[] = [
  {
    id: 'j1',
    clientId: 'c1',
    date: new Date('2025-12-07T18:30:00'),
    zone: 'green',
    energyGivers: ['Playing with friends', 'Drawing'],
    energyDrainers: ['Loud noises at lunch'],
    relaxingActivity: 'Quiet time with puzzles',
    notes: 'Good day overall. Alex was excited about his new dinosaur book from the library.',
    tags: ['school', 'social', 'sensory'],
    loggedBy: 'Sarah Johnson (Mom)',
  },
  {
    id: 'j2',
    clientId: 'c1',
    date: new Date('2025-12-06T19:00:00'),
    zone: 'yellow',
    energyGivers: ['Art class'],
    energyDrainers: ['Transition to homework time', 'Sibling argument'],
    relaxingActivity: 'Deep breathing with mom',
    notes: 'Had a meltdown during homework. We took a break and tried again later with success.',
    tags: ['homework', 'transitions', 'regulation'],
    loggedBy: 'Sarah Johnson (Mom)',
  },
  {
    id: 'j3',
    clientId: 'c1',
    date: new Date('2025-12-05T17:45:00'),
    zone: 'green',
    energyGivers: ['Playground', 'Building with blocks'],
    energyDrainers: [],
    relaxingActivity: 'Reading before bed',
    notes: 'Great day! Alex initiated play with a classmate at recess.',
    tags: ['school', 'social', 'milestone'],
    loggedBy: 'Sarah Johnson (Mom)',
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: 'al1',
    timestamp: new Date('2025-12-08T10:30:00'),
    userId: '1',
    userName: 'Anna Martinez',
    action: 'Created',
    resourceType: 'Session',
    resourceId: 's1',
    details: 'Created session #16 for Alex Johnson',
  },
  {
    id: 'al2',
    timestamp: new Date('2025-12-08T09:15:00'),
    userId: '1',
    userName: 'Anna Martinez',
    action: 'Updated',
    resourceType: 'Goal',
    resourceId: 'g1',
    details: 'Updated progress for goal "Improve Expressive Language" to 65%',
  },
  {
    id: 'al3',
    timestamp: new Date('2025-12-07T14:20:00'),
    userId: '3',
    userName: 'David Williams',
    action: 'Created',
    resourceType: 'Homework',
    resourceId: 'h3',
    details: 'Assigned homework "Pencil Grip Practice" to Michael Brown',
  },
];

export function switchUser(userId: string) {
  const user = users.find(u => u.id === userId);
  if (user) {
    currentUser = user;
  }
}
